# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heartuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userchats.Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartuser.HeartUser')),
            ],
        ),
    ]
