# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heartuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('ethnicity', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('pets', models.CharField(max_length=30)),
                ('kids', models.CharField(max_length=30)),
                ('willingtorelocate', models.BooleanField()),
                ('willingtotravel', models.BooleanField()),
                ('opentodistrelationship', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='heartuser',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='heartuser.Profile'),
        ),
    ]
